name: Hello World

on:
  workflow_dispatch:

jobs:
  print-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Define and print a variable
        run: |
          MY_VARIABLE="Hello, World!"
          echo "The value of MY_VARIABLE is: $MY_VARIABLE"
          URL_BASE="https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/x86_64/"
          OS_VERSION="alpine-minirootfs-"
          OS_TYPE="-x86_64"
          EXT=".tar.gz"
          LAST_VERSION="$(curl -s https://raw.githubusercontent.com/AtomyCloud/docker-images/main/.github/workflows/alpine/last_version.txt | tail -n 1)"
          URL="${URL_BASE}${OS_VERSION}${LAST_VERSION}${OS_TYPE}${EXT}"
          FILE="${OS_VERSION}${LAST_VERSION}${OS_TYPE}${EXT}"
          DOCKER_HUB_REPO="atomycloud/os:"
          TAG_VERSION="${DOCKER_HUB_REPO}${OS_VERSION}${LAST_VERSION}${OS_TYPE}"
          echo "FILE: $FILE"
          echo "DOCKER_HUB_REPO: $DOCKER_HUB_REPO"
          echo "TAG_VERSION: $TAG_VERSION"

      - name: 🪲 Debug
        run: |
          echo "FILE: $FILE"
          echo "DOCKER_HUB_REPO: $DOCKER_HUB_REPO"
          echo "TAG_VERSION: $TAG_VERSION"    

