name: Create Version File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create or append to last_version.txt
      run: echo "3.20.2" >> last_version.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add last_version.txt
        git commit -m "Update last_version.txt with version 3.20.2"
        git push
