name: Create Version File

on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create or append to last_version.txt
      run: echo "3.20.0" >> test.txt
