name: Test 3

permissions:
  actions: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create or append to last_version.txt
      run: | 
        VERSION="3.20.0"
        echo  >> alpine/generic/last_version.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "💫Update last_version.txt with version $VERSION"
        git push
